<?php
extract($_GET);
extract($_POST);
extract($_SERVER);
$toName="이태협";
$toMail="lth83@naver.com";
$mail_content=$question;
$subject="[제작의뢰]_".$ucompany."/".$uname;
$fromCompany=$ucompany;
$fromName=$uname;
$fromNumber=$unumber;
$fromMail=$uemail;
$headers="Return-Path: <".$fromMail.">\n";
$headers.="From: ".$fromName." <".$fromMail.">\n";
$headers.="X-Sender: <".$fromMail.">\n";
$headers.="X-Mailer: PHP\n";
$headers.="Reply-To: ".$fromName." <".$fromMail.">\n";
$headers.="MIME-Version: 1.0\n";
$headers.="Content-Type: text/html;charset=utf-8\n";

$mail_content = "<html>";
$mail_content .= "<head>";
$mail_content .= "<meta http-equiv='Content-Type' content='text/html; charset=utf-8'/>";
$mail_content .= "<style type='text/css'>";
$mail_content .= "body, table, tr, td, select, textarea, input  { font-family: '돋움' , 'arial', 'vardana'; font-size: 9pt;  color: #737373; }";
$mail_content .= "body				{	margin-top: 0px; margin-right: 0px; margin-bottom: 0px; margin-left: 0px;						}";
$mail_content .= ".de_bg			{background-image:  url('images/_bg.gif');";
$mail_content .= "						background-repeat:	repeat-x;";
$mail_content .= "						background-position: left top;  }";
$mail_content .= ".sub_bg						{background-image:  url('images/_bg1.gif');";
$mail_content .= "						background-repeat:	repeat-x;";
$mail_content .= "						background-position: left top;  }";
$mail_content .= "A:visited	{COLOR: #484848; TEXT-DECORATION: none}";
$mail_content .= "A:link			{COLOR: #484848; TEXT-DECORATION: none}";
$mail_content .= "A:active		{COLOR: #484848; TEXT-DECORATION: none}";
$mail_content .= "A:hover		{COLOR: #484848; TEXT-DECORATION: underline}";
$mail_content .= ".cs_no					{font-family: 'Arial' ; font-size:8pt;  color:#727272;  text-align:center;  height:28; }";
$mail_content .= ".cs_no2					{font-family: 'Arial' ; font-size:8pt;  color:#727272;   height:28; }";
$mail_content .= ".cs_no3					{font-family: 'Arial' ; font-size:8pt;  color:#AD91D1;   height:24; text-align:center;  }";
$mail_content .= ".cs_date				{font-family: 'Arial' ; font-size:8pt;  color:#727272;  text-align:center }";
$mail_content .= ".cs_title					{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:6D737F;		text-decoration: none; padding:2 0 0 10}";
$mail_content .= ".cs_title a:link   		{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:6D737F;		text-decoration: none}";
$mail_content .= ".cs_title a:visited		{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:6D737F;		text-decoration: none}";
$mail_content .= ".cs_title a:hover		{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:9C9C9C;		text-decoration: underline}";
$mail_content .= ".cs_name				{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:666666;  text-align:center; padding:4 0 0 0}";
$mail_content .= ".cs_name2				{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:666666;   padding:4 0 0 2; height:28}";
$mail_content .= ".cs_de					{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:666666; font-weight:bold; letter-spacing:-1px; text-align:center; padding:4 0 0 0}	";
$mail_content .= ".cs_de2					{font-family: '굴림', 'Arial' , 'Verdana'; font-size: 9pt;  color:666666; font-weight:bold; letter-spacing:-1px;  padding:4 0 0 15; height:30}	";
$mail_content .= "</style>";
$mail_content .= "</head>";
$mail_content .= "<body>";
$mail_content .= "<table width='660'  border='0' cellspacing='0' cellpadding='0' >";
$mail_content .= "<tr>";
$mail_content .= "<td height='1' bgcolor='BDBDBD'colspan='9'></td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td class='cs_de2' bgcolor='efefef' colspan='9'>다음과 같은 내용의 문의가 접수 되었습니다.</td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td height='1' bgcolor='BDBDBD'colspan='9'></td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td height='30' class='cs_de'><strong>회사명</strong></td>";
$mail_content .= "<td width='1' valign='bottom'></td>";
$mail_content .= "<td class='cs_no2 pl15 pt3'>" . $ucompany . "</td>";
$mail_content .= "<td class='cs_de' ><strong>성함</strong></td>";
$mail_content .= "<td width='1' valign='bottom'></td>";
$mail_content .= "<td class='pl12 pt3'>" . $uname . "</td>";
$mail_content .= "<td class='cs_de' ><strong>등록일</strong></td>";
$mail_content .= "<td width='1' valign='bottom'></td>";
$mail_content .= "<td class='cs_no2 pl12 pt3'>" . date('Y-m-d') . "</td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td height='30' class='cs_de'><strong>연락처</strong></td>";
$mail_content .= "<td valign='bottom'></td>";
$mail_content .= "<td class='cs_no2 pl15 pt3'>" . $unumber . "</td>";
$mail_content .= "<td class='cs_de' ><strong>이메일</strong></td>";
$mail_content .= "<td valign='bottom'></td>";
$mail_content .= "<td class='pl12 pt3'>" . $uemail . "</td>";
$mail_content .= "<td class='cs_de' ><strong></strong></td>";
$mail_content .= "<td valign='bottom'></td>";
$mail_content .= "<td class='cs_no2 pl12 pt3'></td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td height='1' bgcolor='BDBDBD'colspan='9'></td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td class='cs_de2' bgcolor='efefef' colspan='9'>문의내용</td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td height='1' bgcolor='BDBDBD'colspan='9'></td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td class='pte15 v140'  colspan='9'>" . nl2br($question) . "</td>";
$mail_content .= "</tr>";
$mail_content .= "<tr>";
$mail_content .= "<td height='2' bgcolor='CFCFCF'  colspan='9'></td>";
$mail_content .= "</tr>";
$mail_content .= "</table>";
$mail_content .= "</body>";
$mail_content .= "</html>";


$rs=@mail("$toName <$toMail>",$subject,$mail_content,$headers);
if($rs)
	echo "{\"result\":\"o\"}";
else
	echo "{\"result\":\"x\"}";
?>